### ISSUE TITLE
How to connect co Kibana

### ISSUE THREAD

**Issue by Industrial** [pires/kubernetes-elk-cluster#14]
Hi!

I'm unsure how to connect to Kibana once running. I have started the Vagrant cluster example and I can access the service from the inside the vbox image but not outside it.

**Comment by Industrial** [comment]
I've come across the `kubectl expose` command and I've tried `kubectl expose rc kibana --port=8081 --target-port=80` but that gives me `Error from server: services "kibana" already exists`.

**Comment by pires** [comment]
As per [`kubectl expose` documentation](http://kubernetes.io/docs/user-guide/kubectl/kubectl_expose/):

```
Take a replication controller, service or pod and expose it as a new Kubernetes Service
```

You may access services from outside the container with [`kubectl port-forward`](http://kubernetes.io/docs/user-guide/kubectl/kubectl_port-forward/) or [`kubectl proxy`](http://kubernetes.io/docs/user-guide/kubectl/kubectl_proxy/).

**Comment by Industrial** [comment]
Kubernetes already assigns a port in the 30000-32767 range. So It should be approachable from within the Vagrant VM. What I am unable to do is approach it from the host system with my web browser.

I run Kubernetes with:

```
cd ~/Code/Code9/kubernetes-vagrant-coreos-cluster;
vagrant halt;
export NODES=1;
export USE_KUBE_UI=true;
export SYNC_FOLDERS=true;
vagrant up;
```

Kubernetes Dashboard tells me:

```
External endpoint
localhost:31689
```

From the host machine, accessing this service doesn't work;
When I do `vagrant ssh node-01` and then `$ netstat -tulpn | grep 31689` I get:

```
tcp6       4      0 :::31689                :::*                    LISTEN      -
```

When I try  e.g. a `wget 0.0.0.0:31689` or `wget localhost:31689` I get no response.

I don't know what to do now :S

**Comment by Krylon360** [comment]
You need to expose a routable port to the pod. 31689 is a internal cluster
port number. You need to set your RC, and service to expose the needed
ports for elk.

Bryce Walter

**Comment by pires** [comment]
Thank you @Krylon360.
