### ISSUE TITLE
Curious as to why this isn't supported/updated anymore?

### ISSUE THREAD

**Issue by xamox** [pires/kubernetes-elk-cluster#17]
This isn't a compliant but just more curiosity.  I've used your elasticsearch in kube which has worked great.  I've also gotten logstash setup in the k8s cluster and is sending logs.  But just wanted to see if there was reasoning behind it (i.e. since only HTTP ingress is supported unless in GCE, not a good option for logstash, etc).  Or just too much to maintain?

I just want to make sure if there are any pitfalls to running logstash in kube so I don't stumble across them myself.

**Comment by pires** [comment]
I don't use it anymore. Check beats, etc.

**Comment by xamox** [comment]
Okay, thanks for the update.  Maybe I need to look more into ingestion nodes then.
