### ISSUE TITLE
Use Secrets to provision Logstash SSL certificates

### ISSUE THREAD

**Issue by pires** [pires/kubernetes-elk-cluster#6]
http://kubernetes.io/v1.0/docs/user-guide/secrets.html

**Comment by pires** [comment]
@wkharold want to help with this?

**Comment by wkharold** [comment]
I will try to get you a pull request in a couple of days.

**Comment by pires** [comment]
Awesome @wkharold.

**Comment by pires** [comment]
@wkharold closing this but let me know if there's any update.
