### ISSUE TITLE
kubernetes-elk-cluster with coreos-kubernetes

### ISSUE THREAD

**Issue by ghost** [pires/kubernetes-elk-cluster#7]
Hi Paulo,

Hope u are doing well ! And thanks for your great repos ! 

I am looking to use the following set of tools with Kubernetes but having some problems with the authentication system on several levels. So I was wondering if you could help to solve how to integrate https://github.com/pires/kubernetes-elk-cluster into the https://github.com/coreos/coreos-kubernetes/ deployment in an easy way.

Here are the components that I would like to use:

Kubernetes Cluster setup: Coreos/AWS/TLS
https://github.com/coreos/coreos-kubernetes/blob/v0.1.0/Documentation/kubernetes-on-aws.md

Reverse Proxying:
- https://github.com/mailgun/vulcand

External Service Discovery:
- https://github.com/timelinelabs/romulus
  Pb: Not dealing with client certificate, so I cannot register new external IPs

Cluster-Monitoring/Addons
- https://github.com/kubernetes/kubernetes/tree/master/cluster/addons/cluster-monitoring/influxdb (for the nodes)
- https://github.com/pires/kubernetes-elk-cluster (for specific services)

UIs visible from a public IP with a basic authentication (having a problem to get the IP public with using the Kube Proxy):
- Kube-UI (with the graph module)
- Graphana (cluster metrics)
- Kibana (custom logs processing)

How could I re-use the ssl certificate deployment of the coreos kurbenetes cluster with your elk replica controllers and services ?

Cheers,
Luc Michalski

**Comment by pires** [comment]
Wow, that's a somewhat complex scenario. I cannot help with reverse-proxying (I would use `nginx` instead of `vulcand`) or Kubernetes monitoring. Those are things you need to tame yourself, take your time to learn about it and play with it.

I can help you debug this repo stuff on top of CoreOS-Kubernetes by CoreOS. Have you tried deploying this as is on said cluster? What are the errors, if any?

**Comment by ghost** [comment]
I am trying it by deploying https://github.com/Samsung-AG/kraken

Keep u updaated in couple of hours, as I finished my other docker containers
